# Generated by Django 3.2 on 2021-04-18 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0003_fileupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
