# Generated by Django 3.2 on 2021-04-18 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0004_fileupload_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='fileupload',
            field=models.FileField(blank=True, upload_to='media'),
        ),
    ]
