# Generated by Django 3.2 on 2021-04-18 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0005_alter_fileupload_fileupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='status',
            field=models.BooleanField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='fileupload',
            field=models.FileField(upload_to=''),
        ),
    ]
