# Generated by Django 3.2 on 2021-04-18 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0006_auto_20210418_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='status',
        ),
    ]
